camera:
  rtsp_url: rtsp://admin:123456@192.168.10.33:554/
  read_timeout_sec: 10
  frame_resize_width: 0
  skip_frames: 3
detector:
  cascade_path: ''
  min_area: 2000
  debug_draw: false
ocr:
  enabled: true
  tesseract_cmd: ''
  psm: 7
  whitelist: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
rules:
  allowed_csv: data/allowed.csv
  denied_csv: data/denied.csv
  watchlist_csv: data/watchlist.csv
  debounce_sec: 15
actions:
  gate:
    mode: dry_run
    http:
      open_url: ''
      close_url: ''
      method: POST
      headers: {}
      payload_template: {}
  alarm:
    mode: dry_run
    http:
      trigger_url: ''
      method: POST
      headers: {}
      payload_template: {}
notify:
  telegram:
    enabled: true
    bot_token: 8463888693:AAHS2xsejdWebakw3DOklRljfR9SwQjOCak
    chat_ids:
    - 6069420562
    group_routes: {}
    send_photos: true
    notify_unreadable: true
    unreadable_debounce_sec: 10
    unreadable_dhash_threshold: 6
    unreadable_global_cooldown_sec: 8
    diagnose_on_start: false
    debug_chat_ids:
    - 6069420562
  telegram_debug:
    enabled: false
    bot_token: ""
    chat_ids: []
logging:
  level: INFO
  forward_to_telegram: false
direction:
  enabled: true
  axis: x
  invert: false
  min_displacement: 162
  gate_line: 342.0
  require_line_cross: false
roi:
  enabled: true
  mode: rectangle
  rect:
  - 219
  - 1
  - 7
  - 211
  polygon: []
notify_filters:
  only_in_direction: false
  unreadable_min_hits: 1
  hit_ttl_sec: 1.0
  center_tolerance_px: 40
notify_routes:
  unreadable: both
  readable: both
